# Generated by Django 3.2.7 on 2021-09-04 07:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلید واژه')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/Category/%Y/%m/%d', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('create_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='به روز شده در')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلید واژه ها')),
                ('brand_name', models.CharField(max_length=255, verbose_name='نام برند')),
                ('model_name', models.CharField(max_length=255, verbose_name='نام مدل')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/Product/%Y/%m/%d/', verbose_name='تصویر')),
                ('slider_image', models.ImageField(upload_to='images/Slider/%Y/%m/%d/', verbose_name='تصویر اسلایدر')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('minAmount', models.PositiveIntegerField(default=3, verbose_name='کمترین مقدار')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات')),
                ('transportation', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حمل و نقل')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('create_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='به روز شده در')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to='images/Product/%Y/%m/%d/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
